### ISSUE TITLE
Create the content for a Trusted Seed Project on Giveth

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#106]
From iteration0 created by [GriffGreen](https://github.com/GriffGreen): commons-stack/iteration0#1345  

## 📋   Anything to add?

Pass it to griff when done to create the actual project 

People will use this to Pay Dues if they are members, or donate if not.

## 🎉   Subtasks

- [x] needs a banner picture
- [x] a couple paragraphs with links

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
Tagging @kristoferlund for visibility 

https://docs.google.com/document/d/1XghbvE8pp8_-J4QXTtDI1skXIf_t0GdrUagtz4lRw90/edit?usp=sharing

**Comment by usama9500** [comment]
@usama9500 This one created after you ran the script to move these to the Trusted Seed Sprint Board. ;)

**Comment by YineisyM** [comment]
I created a new version for the texts in our project on Giveth, I'm just waiting for  feedback: https://docs.google.com/document/d/1XghbvE8pp8_-J4QXTtDI1skXIf_t0GdrUagtz4lRw90/edit?usp=sharing 

@GriffGreen @mafer-cordovas @iviangita

**Comment by YineisyM** [comment]
I created a new version for the texts in our project on Giveth, I'm just waiting for  feedback: https://docs.google.com/document/d/1XghbvE8pp8_-J4QXTtDI1skXIf_t0GdrUagtz4lRw90/edit?usp=sharing 

@GriffGreen @mafer-cordovas @iviangita

**Comment by YineisyM** [comment]
The text was recently changed in the project. I'm closing this issue.
