### ISSUE TITLE
 3rd TS Renewal Notice

### ISSUE THREAD

**Issue by YineisyM** [Trusted-Seed/coordination#128]
## 📋   Anything to add?

Create the third and final notification to inform that there are only 30 days left to renew their memberships.

## 🎉   Subtasks

- [x] Draft the message 
- [ ] Exclude who already renewed
- [ ] Send it

## 🔗   Work doc - inspirational links

https://docs.google.com/document/d/15OqTkwaXYyMjUWytXTZgTQoLATNqZX6OsBkCGXzox4w/edit?usp=sharing

**Comment by mafer-labs** [comment]
Email sent on June 6.
