### ISSUE TITLE
New CSA Swiss address

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#17]
From iteration0 created by [iviangita](https://github.com/iviangita): commons-stack/iteration0#1250  

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
New updates in this document: https://docs.google.com/spreadsheets/d/1ErDHV-ZiRriREn22esFsHw_m9rHkP26sAU_Pst8pGkE/edit?usp=sharing

Still trying to get the final votes from the Board

**Comment by iviangita** [comment]
This is done, we can close this! The next step is to get the vote from the Association members during the General Assembly. I will open a new issue for the Assembly.
