### ISSUE TITLE
Terms Updates (in connection to renewal)?

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#18]
From iteration0 created by [MaxSemenchuk](https://github.com/MaxSemenchuk): commons-stack/iteration0#1247  

## 📋   Anything to add?
- Grace period
- Activation dates clarification

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
Successful applicant email >
[https://app.zenhub.com/files/280516198/6ff76e83-9b2e-4afc-96fa-bffb72071387/download](https://app.zenhub.com/files/280516198/6ff76e83-9b2e-4afc-96fa-bffb72071387/download)

**Comment by usama9500** [comment]
I edited the document to integrate the latest updates in the membership period and renewal process. @mafer-cordovas kindly review and let me know if there's anything I missed or if you find something inaccurate. Thanks! :)

https://docs.google.com/document/d/1IRokda-cbiKuip9jtFLVHb5T57tk96duONVqrCqg3Uo/edit?usp=sharing

**Comment by iviangita** [comment]
Closing! Here's the revised version w/ help from Griff, Tam and Mafer: https://docs.google.com/document/d/1IRokda-cbiKuip9jtFLVHb5T57tk96duONVqrCqg3Uo/edit?usp=sharing. I also consulted Raphael about excluding the info about the membership types from the previous version. Already shared this with Fabio in May to be integrated in the membership dapp
