### ISSUE TITLE
Membership Termination Process

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#35]
From iteration0 created by [mafer-cordovas](https://github.com/mafer-cordovas): commons-stack/iteration0#1159  

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by usama9500** [comment]
#345 is worth reviewing

**Comment by usama9500** [comment]
Draft for the wiki https://docs.google.com/document/d/1wKyUGQC53JLzNG0ToJ0aN78z1tEi9nNIfb0QOAZxjQM/edit#

**Comment by usama9500** [comment]
Will be published on the wiki and a notion for internal use

**Comment by usama9500** [comment]
Needs to be revisited for nonpayment of renewal.

**Comment by usama9500** [comment]
https://docs.google.com/document/d/1IRokda-cbiKuip9jtFLVHb5T57tk96duONVqrCqg3Uo/edit?usp=sharing

@iviangita has updated the T&C to add the update on nonpayment. 

As soon as these changes are voted by the board. A new Gitbook for the Trusted Seed must be created to publish the membership termination conditions.

**Comment by tamarandom** [comment]
Assigning to myself until Maria is able to accept Github issue.

**Comment by mafer-labs** [comment]
Put this on the new wiki for TS.
