### ISSUE TITLE
Adjust application typeform

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#59]
From iteration0 created by [kristoferlund](https://github.com/kristoferlund): commons-stack/iteration0#1314  

null

**Comment by usama9500** [comment]
https://trusted-seed-dashboard.netlify.app/apply-stage-two

- Remove CS logo
- Remove first screen or change text
- Adjust form colors to match website theme colors. Use #12BAD6 is possible
- Can we get rid of "Powered by typeform"?

**Comment by YineisyM** [comment]
Will this link be obsolete after the launch of the dashboard? http://commonsstack.org/apply 

If so, I need your confirmation if I can do this modification in the Typeform @kristoferlund @mafer-cordovas

**Comment by YineisyM** [comment]
I noticed that a new Typeform was created for the dashboard. I'm closing this issue.
