### ISSUE TITLE
Connecting more than 1 sending domains in HubSpot

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#6]
From iteration0 created by [YineisyM](https://github.com/YineisyM): commons-stack/iteration0#1288  

## 📋   Anything to add?

Thinking of creating an email intended only for Trusted Seed matters, we were reviewing what would be the best process for better deliverability for the upcoming campaigns.

## 🎉   Subtasks

- [ ] Opened a Ticket with HubSpot
- [ ] Decide the best way to go

## 🤼‍♂️   Reviewer

@

**Comment by YineisyM** [comment]
Here's the information related with the DNS so we can connect more than 1 sending domain in HubSpot, but we need to upgrade our marketing plan in order to achieve this.

Connecting our email sending domains will help prevent our marketing emails from getting caught in spam filters,

@kristoferlund @GriffGreen @mafer-cordovas

**Comment by kristoferlund** [comment]
> we need to upgrade our marketing plan in order to achieve this.

@YineisyM, what would be the cost for this upgrade?

**Comment by YineisyM** [comment]
@kristoferlund 

Upfront: Starts at $45/mo billed at $600 $540/yr
Monthly: $50/mo billed monthly.

It includes:

Free tools with increased limits, plus:

REMOVE HUBSPOT BRANDING FROM
- Forms
- Email marketing
- Landing pages
- Live chat

GET HELP FAST

- Email and in-app chat support

WORKFLOWS

- HubSpot recently incorporated simple workflows feature ( allowing us having email automations) with this plan.

More info:
https://www.hubspot.com/products/marketing/starter

**Comment by YineisyM** [comment]
@mafer-cordovas @MaxSemenchuk @GriffGreen we need to discuss this about the pros and cons already mentioned in this issue and decide whether to pay for the plan or not.

We must also verify if we can use the email info@trustedseed.org to send our communications.

**Comment by YineisyM** [comment]
We now have an email provider and can start using it in HubSpot: info@trustedseed.org. However, we are unable to connect it to HubSpot as we need to upgrade our current plan and it is not possible given our current budget. I will close this issue until then.
