### ISSUE TITLE
Migrate from CSTK to a trusted seed token

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#66]
From iteration0 created by [kristoferlund](https://github.com/kristoferlund): commons-stack/iteration0#1279  

## 📋   Anything to add?

Making the distiction between CS and TS clearer should affect the CTSK token as well. Let's create a new trust token and retire CSTK.

**Comment by GriffGreen** [comment]
Still need to get the Membership DApp using the new token, also need to create $TRUST for people who minted this week
