### ISSUE TITLE
TS Association Board

### ISSUE THREAD

**Issue by usama9500** [Trusted-Seed/coordination#86]
From iteration0 created by [kristoferlund](https://github.com/kristoferlund): commons-stack/iteration0#1183  

## Details
- Message: A short text about the association being headed by a board.
- Fact: Number of board members
- Link: Link to GitBook or own page:

## Open questions
- Content needed @mafer-cordovas 
- For the page component
- … and for the GitBook / webpage describing the board 
  - Members
  - How does decisions get made
  - etc
  

## 💭 Who should be part of Advice Process on this issue

@GriffGreen - board information

## 🔗 The links and docs related to this issue

**Comment by kristoferlund** [comment]
@iviangita, could you write a short text about the TS Association board? Like.. two sentences. 

And, do we have somewhere to link for the `Read More` link?

<img width="827" alt="image" src="https://user-images.githubusercontent.com/9698363/169905877-af339544-d21f-42e5-815f-7132d6d5db4e.png">
